"""Add role field to user models

Revision ID: 4fec80cbcd66
Revises: 
Create Date: 2025-02-27 08:28:15.932732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fec80cbcd66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election_officer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('system_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('system_admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('election_officer', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
